tube_diameter: 1.59   # mm inner diameter of tube
syringe_diameter: 35  # mm inner diameter of syringe
max_vol: 100           # mL max volume of syringe
total_rate: 20         # mL min-1 total flow rate
total_time: 30        # min total time
total_length: 200    # mm tube length
alarm_time: 3         #    times of residence time passed, alart
slug_volume: [60, 60] # uL slug volume
response_time: 0.01    # s waiting the response
gpio_pin: [6, 13, 19, 26]  # gpio pin number
# gpio_pin: [6, 13] # gpio pin number
serial_port: ['/dev/ttyACM0', '/dev/ttyACM1'] # serial port address
baudrate: 115200      # baudrate
#delay: [
#    [0.0, 0.0],
#    [0.0, 0.0]
#]
delay: [
  [-0.02, 0.02],    # delay of valve0(open, close)
  [-0.02, 0.02],    # delay of valve1(open, close)
  [0, 0],    # delay of valve2(open, close)
  [0, 0]    # delay of valve3(open, close)
]
